### ISSUE TITLE
Null pointer exeception

### ISSUE THREAD

**Issue by anandinmaddy** [FreesoulApps/PreviewAndroid#2]
Fatal Exception: java.lang.NullPointerException: println needs a message
       at android.util.Log.println_native(Log.java)
       at android.util.Log.e(Log.java:232)
       at com.freesoulapps.preview.android.Preview$7.onFailure(Preview.java:168)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:185)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by alexglobalbit** [comment]
Should be fixed in version 0.3.3
